management:
    health:
        diskspace:
            enabled: false
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: prometheus, health
            base-path: '/'
            path-mapping:
                prometheus: 'metrics'
